FROM golang:1.22-alpine AS builder

WORKDIR /app
RUN apk add --no-cache curl tar

ARG MIHOMO_VERSION

RUN curl -L https://github.com/MetaCubeX/mihomo/archive/refs/tags/v${MIHOMO_VERSION}.tar.gz \
    -o mihomo.tar.gz \
 && tar -xzf mihomo.tar.gz --strip-components=1

RUN CGO_ENABLED=0 go build -ldflags "-s -w" -o mihomo

FROM alpine:latest
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/mihomo /usr/local/bin/mihomo

CMD ["mihomo"]
