FROM node:20-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

RUN git clone --depth=1 https://github.com/MetaCubeX/metacubexd.git .

RUN npm ci || npm install

ENV NUXT_FONT_DOWNLOAD=false

RUN npm run generate

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/.output/public /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
