FROM node:20-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

RUN git clone https://github.com/MetaCubeX/metacubexd.git .

RUN npm install
RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
