name: Build Local Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v4

      - name: Prepare mihomo
        run: |
          docker pull metacubex/mihomo:latest
          docker tag metacubex/mihomo:latest mihomo:local
          docker rmi metacubex/mihomo:latest

      - name: Prepare metacubexd
        run: |
          docker pull ghcr.io/metacubex/metacubexd:latest
          docker tag ghcr.io/metacubex/metacubexd:latest metacubexd:local
          docker rmi ghcr.io/metacubex/metacubexd:latest

      - name: Save images
        run: |
          docker save mihomo:local -o mihomo.tar
          docker save metacubexd:local -o metacubexd.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: docker-images
          path: |
            mihomo.tar
            metacubexd.tar
